name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  project:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Install deps
        run: make install

      - name: Run module
        run: .venv/bin/python -m starter 10
